In [1]:
#!pip install selenium

# o instalalo desde conda como tu decidas

In [2]:
#!pip install webdriver-manager

In [1]:
import requests
from bs4 import BeautifulSoup as bs
# from selenium import webdriver
# from webdriver_manager.chrome import ChromeDriverManager


import re # Expresiones regulares 
import time
import numpy as np
import pandas as pd

In [ ]:
url = "https://chilepropiedades.cl/propiedades/venta-usada/departamento/region-metropolitana-de-santiago-rm/0"


response = requests.get(url, 
                        headers= {"User-Agent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"}
                        )

In [5]:
html = response.content

In [6]:
soup = bs(html, "lxml")

In [7]:
casas = soup.select("div.position-relative.d-sm-flex")

In [8]:
len(casas)

10

## Individual Case

In [9]:
url = "https://chilepropiedades.cl/propiedades/venta-usada/casa/region-metropolitana-de-santiago-rm/4"


response = requests.get(url, 
                        headers= {"User-Agent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"}
                        )
time.sleep(1)

html = response.content
soup = bs(html, "lxml")
casas = soup.select("div.position-relative.d-sm-flex")

In [10]:
casas[7].select("h2.publication-title-list a")[0].get_text().split("\n")[1].strip()# direccion

'Estación Central, Gloria 472'

In [11]:
casas[6].select("span.clp-value-container") # precio

[<span areaunit="" class="clp-value-container" data-no-value="" valueunit="3">
                     UF
                   </span>,
 <span areaunit="" class="clp-value-container" data-no-value-unit="" value="7180.0" valueunit="3">
                     7.180
                   </span>]

In [12]:
if casas[0].select("span.clp-value-container")[0].get_text(strip=True) == "$":
    price = int(casas[0].select("span.clp-value-container")[1].get_text(strip=True).replace(".",""))
    price
    print(round(price / 34823, 3))
elif casas[0].select("span.clp-value-container")[0].get_text(strip=True) == "UF":
    price = int(casas[0].select("span.clp-value-container")[1].get_text(strip=True).replace(".",""))
    print(price)
    print(round(price * 34823, 3))
elif casas[0].select("span.clp-value-container")[0].get_text(strip=True) == "USD":
    price = int(casas[0].select("span.clp-value-container")[1].get_text(strip=True).replace(".",""))
    print(price)
    print(round(price * 34823, 3))

20900
727800700

In [13]:
int(casas[2].select("span.clp-value-container")[1].get_text(strip=True).replace(".",""))

185000000

In [14]:
len(casas[6].select("div.clp-publication-features-container span"))

15

In [15]:
categorias = casas[8].select("div.clp-publication-features-container span")
categorias_clean = [i.get_text(strip=True).split(":")[0] for i in categorias]
check_hab_bath = ["Baños", "Habitaciones"]

In [16]:
[i in categorias_clean for i in check_hab_bath]

[True, True]

In [17]:
if not(all([i in categorias_clean for i in check_hab_bath])):
    continue

SyntaxError: 'continue' not properly in loop (3620313749.py, line 2)

In [ ]:

if ("Habitaciones" and "Baños") in [i.get_text(strip=True).split(":")[0] for i in categorias]:
    print("gloria la bravo pueblo")

gloria la bravo pueblo

In [ ]:
("Habitaciones" and "Baños") in [i.get_text(strip=True).split(":")[0] for i in categorias]

True

In [ ]:
for i in casas[8].select("div.clp-publication-features-container span"):
    print(i.get_text(strip=True).split(":")[0])

Baños
Baños
2
Superficie Construida
Superficie Construida
98 m²
|
Terreno
98 m²
Estacionamientos
Estacionamientos
2

In [ ]:
bla = casas[4].select("div.clp-publication-features-container span")[6].select("span.clp-feature-value")# para casa que tienen tanto superficie construida y total 
bla

[<span class="clp-feature-value" title="Superficie Construida">70 m²</span>,
 <span class="clp-feature-value" title="Superficie Total">122 m²</span>]

In [ ]:

#metros_cons=[]
#total_metros=[]

if len(bla) == 1:
    pass
    # all_metros_coin.append(int(bla[0].get_text().split()[0])
    # all_metros_totales.append(int(bla[0].get_text().split()[0])
elif len(bla) == 2:
    print(float(bla[0].get_text().replace(",",".").split()[0]))
    print(bla[1].get_text().replace(",","."))

70.0
122 m²

In [ ]:
casas[0].select("div.clp-publication-features-container span")[2].get_text() # habitacion

'3'

In [ ]:
casas[0].select("div.clp-publication-features-container span")[5].get_text() # Baños

'1'

In [ ]:
if casas[0].select("div.clp-publication-features-container span")[-2].get_text() == 'Estacionamientos:':  # Estacionamientos
    a = casas[0].select("div.clp-publication-features-container span")[-1].get_text()
else:
    a = 0
a

'2'

In [ ]:
casas[0].select("div.text-center")[0].get_text().split("\n")[1] #  fecha

'02/12/2022'

## Just one pag

In [2]:
url = "https://chilepropiedades.cl/propiedades/venta-usada/departamento/region-metropolitana-de-santiago-rm/0"


response = requests.get(url, 
                        headers= {"User-Agent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"}
                        )
# time.sleep(1)

html = response.content
soup = bs(html, "lxml")
casas = soup.select("div.position-relative.d-sm-flex")

In [3]:
solo_address = []
solo_price = []
solo_uf = []
solo_cons_m2 = []
solo_total_m2 = []
solo_num_bedrooms = []
solo_num_bathrooms = []
solo_parkings_slots = []
solo_publi_date = []

In [4]:
for idx,cas in enumerate(casas):
    # print(idx)
    categorias = cas.select("div.clp-publication-features-container span")
    categorias_clean = [i.get_text(strip=True).split(":")[0] for i in categorias]
    check_hab_bath = ["Baños", "Habitaciones"]
    
    if not(all([i in categorias_clean for i in check_hab_bath])):
        continue

    solo_address.append(cas.select("h2.publication-title-list a")[0].get_text().split("\n")[1].strip())

    if cas.select("span.clp-value-container")[0].get_text(strip=True) == "$":
        price = int(cas.select("span.clp-value-container")[1].get_text(strip=True).replace(".",""))
        print(idx,price)
        solo_price.append(price)
        solo_uf.append(round(price / 34829, 3))
    elif cas.select("span.clp-value-container")[0].get_text(strip=True) == "UF":
        price = int(cas.select("span.clp-value-container")[1].get_text(strip=True).replace(".",""))
        print(idx,price)
        solo_uf.append(price)
        solo_price.append(round(price * 34829, 3))

    elif cas.select("span.clp-value-container")[0].get_text(strip=True) == "USD":
        price = int(cas.select("span.clp-value-container")[1].get_text(strip=True).replace(".",""))
        print(idx,price, price / 39, price * 886)
        solo_uf.append(round(price / 39, 3))
        solo_price.append(round(price * 886, 3))


    categorias = cas.select("div.clp-publication-features-container span")
    if "Terreno" in [i.get_text(strip=True).split(":")[0] for i in categorias]:
        meters = cas.select("div.clp-publication-features-container span")[6].select("span.clp-feature-value")

        if len(meters) == 1:
            solo_cons_m2.append(int(meters[0].get_text().split(",")[0].replace(".","").split()[0]))
            solo_total_m2.append(int(meters[0].get_text().split(",")[0].replace(".","").split()[0]))
        elif len(meters) == 2:
            solo_cons_m2.append(int(meters[0].get_text().split(",")[0].replace(".","").split()[0]))
            solo_total_m2.append(int(meters[1].get_text().split(",")[0].replace(".","").split()[0]))
    else:
        solo_cons_m2.append(0)
        solo_total_m2.append(0)

    
    solo_num_bedrooms.append(int(cas.select("div.clp-publication-features-container span")[2].get_text()))
    solo_num_bathrooms.append(int(cas.select("div.clp-publication-features-container span")[5].get_text()))

    if cas.select("div.clp-publication-features-container span")[-2].get_text() == 'Estacionamientos:':  # Estacionamientos
        solo_parkings_slots.append(int(cas.select("div.clp-publication-features-container span")[-1].get_text()))
    else:
        solo_parkings_slots.append(0)
    
    solo_publi_date.append(cas.select("div.text-center")[0].get_text().split("\n")[1])

0 6892
1 2800
2 2500
3 87000000
4 68000000
5 4800
6 9900
7 2200
8 115000000
9 100000000

In [5]:
dict_data = {"Direccion": solo_address,
             "Precio" : solo_price,
             "UF" : solo_uf,
             "m2_Construidos" : solo_cons_m2,
             "m2_totales" : solo_total_m2,
             "Habitaciones" :  solo_num_bedrooms,
             "Banos" : solo_num_bathrooms,
             "Estacionamientos" : solo_parkings_slots,
             "Publi": solo_publi_date}

In [ ]:
solo_price

[121553210,
 115000000,
 76240681,
 602541700,
 68000000,
 119990000,
 2020080000,
 68000000,
 228000000,
 99000000]

In [6]:
full_list = [solo_address, solo_price, solo_uf, solo_cons_m2, solo_total_m2, solo_num_bedrooms, solo_num_bathrooms, solo_parkings_slots, solo_publi_date]
len_full = np.array([len(i) for i in full_list])
len_full

array([10, 10, 10, 10, 10, 10, 10, 10, 10])

In [7]:
# Two ways of doing the same thing
# Check if all the values are the same

np.count_nonzero(len_full == len_full[0]) == len(len_full)
f"all_ elements are equal : {np.unique(len_full).shape[0] == 1}"

'all_ elements are equal : True'

In [8]:
pd.DataFrame(dict_data)

,Direccion,Precio,UF,m2_Construidos,m2_totales,Habitaciones,Banos,Estacionamientos,Publi
0,"Providencia, ¡Mira! Aquí está, Carmen Sylva / ...",240041468,6892.000,86,86,2,3,1,19/12/2022
1,"Santiago, Sta. Isabel 431",97521200,2800.000,48,48,2,2,0,18/12/2022
2,"La Florida, Tobalaba 7321",87072500,2500.000,55,55,3,2,1,18/12/2022
3,"Las Condes, Vital Apoquindo",87000000,2497.918,0,0,3,1,0,18/12/2022
4,"Quinta Normal, Carrascal",68000000,1952.396,0,0,2,1,0,18/12/2022
5,"Ñuñoa, José Domingo Cañas 2277",167179200,4800.000,54,54,2,2,0,17/12/2022
6,"Vitacura, Mar jónico",344807100,9900.000,114,114,3,3,2,17/12/2022
7,"Estación Central, Avenida libertador bernardo ...",76623800,2200.000,0,0,3,1,0,16/12/2022
8,"Santiago, Avenida Portugal 415",115000000,3301.846,60,60,2,2,0,16/12/2022
9,"San Miguel, Av. Centenario 1000",100000000,2871.171,48,48,2,1,1,16/12/2022

# Prueba de Fuego

In [48]:
all_address = []
all_price = []
all_uf = []
all_cons_m2 = []
all_total_m2 = []
all_num_bedrooms = []
all_num_bathrooms = []
all_parkings_slots = []
all_publi_date = []

In [49]:
full_list = [all_address, all_price, all_uf, all_cons_m2, all_total_m2, all_num_bedrooms, all_num_bathrooms, all_parkings_slots, all_publi_date]

In [50]:
for i in range(0,1000):
    url = f"https://chilepropiedades.cl/propiedades/venta-usada/departamento/region-metropolitana-de-santiago-rm/{i}"


    response = requests.get(url, 
                            headers= {"User-Agent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"}
                            )
    # time.sleep(1)

    html = response.content
    soup = bs(html, "lxml")
    casas = soup.select("div.position-relative.d-sm-flex")

    for cas in casas:
        categorias = cas.select("div.clp-publication-features-container span")
        categorias_clean = [i.get_text(strip=True).split(":")[0] for i in categorias]
        check_hab_bath = ["Baños", "Habitaciones"]
        
        if not(all([i in categorias_clean for i in check_hab_bath])):
            continue
        #####
        all_address.append(cas.select("h2.publication-title-list a")[0].get_text().split("\n")[1].strip())

        if cas.select("span.clp-value-container")[0].get_text(strip=True) == "$":
            price = int(cas.select("span.clp-value-container")[1].get_text(strip=True).replace(".",""))
            all_price.append(price)
            all_uf.append(round(price / 34823, 3))
        elif cas.select("span.clp-value-container")[0].get_text(strip=True) == "UF":
            price = int(cas.select("span.clp-value-container")[1].get_text(strip=True).replace(".",""))
            all_uf.append(price)
            all_price.append(round(price * 34823, 3))
        elif cas.select("span.clp-value-container")[0].get_text(strip=True) == "USD":
            price = int(cas.select("span.clp-value-container")[1].get_text(strip=True).replace(".",""))
            all_uf.append(round(price / 39, 3))
            all_price.append(round(price * 886, 3))

        categorias = cas.select("div.clp-publication-features-container span")
        if "Terreno" in [i.get_text(strip=True).split(":")[0] for i in categorias]:
            meters = cas.select("div.clp-publication-features-container span")[6].select("span.clp-feature-value")

            if len(meters) == 1:
                all_cons_m2.append(int(meters[0].get_text().split(",")[0].replace(".","").split()[0]))
                all_total_m2.append(int(meters[0].get_text().split(",")[0].replace(".","").split()[0]))
            elif len(meters) == 2:
                all_cons_m2.append(int(meters[0].get_text().split(",")[0].replace(".","").split()[0]))
                all_total_m2.append(int(meters[1].get_text().split(",")[0].replace(".","").split()[0]))
        else:
            all_cons_m2.append(0)
            all_total_m2.append(0)
            
        all_num_bedrooms.append(int(cas.select("div.clp-publication-features-container span")[2].get_text()))
        all_num_bathrooms.append(int(cas.select("div.clp-publication-features-container span")[5].get_text()))

        if cas.select("div.clp-publication-features-container span")[-2].get_text() == 'Estacionamientos:':  # Estacionamientos
            all_parkings_slots.append(int(cas.select("div.clp-publication-features-container span")[-1].get_text()))
        else:
            all_parkings_slots.append(0)
        
        all_publi_date.append(cas.select("div.text-center")[0].get_text().split("\n")[1])

    len_full = np.array([len(i) for i in full_list])
    print(i, f"all_ elements are equal : {np.unique(len_full).shape[0] == 1}")

0 all_ elements are equal : True
1 all_ elements are equal : True
2 all_ elements are equal : True
3 all_ elements are equal : True
4 all_ elements are equal : True
5 all_ elements are equal : True
6 all_ elements are equal : True
7 all_ elements are equal : True
8 all_ elements are equal : True
9 all_ elements are equal : True
10 all_ elements are equal : True
11 all_ elements are equal : True
12 all_ elements are equal : True
13 all_ elements are equal : True
14 all_ elements are equal : True
15 all_ elements are equal : True
16 all_ elements are equal : True
17 all_ elements are equal : True
18 all_ elements are equal : True
19 all_ elements are equal : True
20 all_ elements are equal : True
21 all_ elements are equal : True
22 all_ elements are equal : True
23 all_ elements are equal : True
24 all_ elements are equal : True
25 all_ elements are equal : True
26 all_ elements are equal : True
27 all_ elements are equal : True
28 all_ elements are equal : True
29 all_ elements are equal : True
30 all_ elements are equal : True
31 all_ elements are equal : True
32 all_ elements are equal : True
33 all_ elements are equal : True
34 all_ elements are equal : True
35 all_ elements are equal : True
36 all_ elements are equal : True
37 all_ elements are equal : True
38 all_ elements are equal : True
39 all_ elements are equal : True
40 all_ elements are equal : True
41 all_ elements are equal : True
42 all_ elements are equal : True
43 all_ elements are equal : True
44 all_ elements are equal : True
45 all_ elements are equal : True
46 all_ elements are equal : True
47 all_ elements are equal : True
48 all_ elements are equal : True
49 all_ elements are equal : True
50 all_ elements are equal : True
51 all_ elements are equal : True
52 all_ elements are equal : True
53 all_ elements are equal : True
54 all_ elements are equal : True
55 all_ elements are equal : True
56 all_ elements are equal : True
57 all_ elements are equal : True
58 all_ elements are equal : True
59 all_ elements are equal : True
60 all_ elements are equal : True
61 all_ elements are equal : True
62 all_ elements are equal : True
63 all_ elements are equal : True
64 all_ elements are equal : True
65 all_ elements are equal : True
66 all_ elements are equal : True
67 all_ elements are equal : True
68 all_ elements are equal : True
69 all_ elements are equal : True
70 all_ elements are equal : True
71 all_ elements are equal : True
72 all_ elements are equal : True
73 all_ elements are equal : True
74 all_ elements are equal : True
75 all_ elements are equal : True
76 all_ elements are equal : True
77 all_ elements are equal : True
78 all_ elements are equal : True
79 all_ elements are equal : True
80 all_ elements are equal : True
81 all_ elements are equal : True
82 all_ elements are equal : True
83 all_ elements are equal : True
84 all_ elements are equal : True
85 all_ elements are equal : True
86 all_ elements are equal : True
87 all_ elements are equal : True
88 all_ elements are equal : True
89 all_ elements are equal : True
90 all_ elements are equal : True
91 all_ elements are equal : True
92 all_ elements are equal : True
93 all_ elements are equal : True
94 all_ elements are equal : True
95 all_ elements are equal : True
96 all_ elements are equal : True
97 all_ elements are equal : True
98 all_ elements are equal : True
99 all_ elements are equal : True
100 all_ elements are equal : True
101 all_ elements are equal : True
102 all_ elements are equal : True
103 all_ elements are equal : True
104 all_ elements are equal : True
105 all_ elements are equal : True
106 all_ elements are equal : True
107 all_ elements are equal : True
108 all_ elements are equal : True
109 all_ elements are equal : True
110 all_ elements are equal : True
111 all_ elements are equal : True
112 all_ elements are equal : True
113 all_ elements are equal : True
114 all_ elements are equal : True
115 all_ elements are equal : True
116 all_ elements are equal : True
117 all_ elements are equal : True
118 all_ elements are equal : True
119 all_ elements are equal : True
120 all_ elements are equal : True
121 all_ elements are equal : True
122 all_ elements are equal : True
123 all_ elements are equal : True
124 all_ elements are equal : True
125 all_ elements are equal : True
126 all_ elements are equal : True
127 all_ elements are equal : True
128 all_ elements are equal : True
129 all_ elements are equal : True
130 all_ elements are equal : True
131 all_ elements are equal : True
132 all_ elements are equal : True
133 all_ elements are equal : True
134 all_ elements are equal : True
135 all_ elements are equal : True
136 all_ elements are equal : True
137 all_ elements are equal : True
138 all_ elements are equal : True
139 all_ elements are equal : True
140 all_ elements are equal : True
141 all_ elements are equal : True
142 all_ elements are equal : True
143 all_ elements are equal : True
144 all_ elements are equal : True
145 all_ elements are equal : True
146 all_ elements are equal : True
147 all_ elements are equal : True
148 all_ elements are equal : True
149 all_ elements are equal : True
150 all_ elements are equal : True
151 all_ elements are equal : True
152 all_ elements are equal : True
153 all_ elements are equal : True
154 all_ elements are equal : True
155 all_ elements are equal : True
156 all_ elements are equal : True
157 all_ elements are equal : True
158 all_ elements are equal : True
159 all_ elements are equal : True
160 all_ elements are equal : True
161 all_ elements are equal : True
162 all_ elements are equal : True
163 all_ elements are equal : True
164 all_ elements are equal : True
165 all_ elements are equal : True
166 all_ elements are equal : True
167 all_ elements are equal : True
168 all_ elements are equal : True
169 all_ elements are equal : True
170 all_ elements are equal : True
171 all_ elements are equal : True
172 all_ elements are equal : True
173 all_ elements are equal : True
174 all_ elements are equal : True
175 all_ elements are equal : True
176 all_ elements are equal : True
177 all_ elements are equal : True
178 all_ elements are equal : True
179 all_ elements are equal : True
180 all_ elements are equal : True
181 all_ elements are equal : True
182 all_ elements are equal : True
183 all_ elements are equal : True
184 all_ elements are equal : True
185 all_ elements are equal : True
186 all_ elements are equal : True
187 all_ elements are equal : True
188 all_ elements are equal : True
189 all_ elements are equal : True
190 all_ elements are equal : True
191 all_ elements are equal : True
192 all_ elements are equal : True
193 all_ elements are equal : True
194 all_ elements are equal : True
195 all_ elements are equal : True
196 all_ elements are equal : True
197 all_ elements are equal : True
198 all_ elements are equal : True
199 all_ elements are equal : True
200 all_ elements are equal : True
201 all_ elements are equal : True
202 all_ elements are equal : True
203 all_ elements are equal : True
204 all_ elements are equal : True
205 all_ elements are equal : True
206 all_ elements are equal : True
207 all_ elements are equal : True
208 all_ elements are equal : True
209 all_ elements are equal : True
210 all_ elements are equal : True
211 all_ elements are equal : True
212 all_ elements are equal : True
213 all_ elements are equal : True
214 all_ elements are equal : True
215 all_ elements are equal : True
216 all_ elements are equal : True
217 all_ elements are equal : True
218 all_ elements are equal : True
219 all_ elements are equal : True
220 all_ elements are equal : True
221 all_ elements are equal : True
222 all_ elements are equal : True
223 all_ elements are equal : True
224 all_ elements are equal : True
225 all_ elements are equal : True
226 all_ elements are equal : True
227 all_ elements are equal : True
228 all_ elements are equal : True
229 all_ elements are equal : True
230 all_ elements are equal : True
231 all_ elements are equal : True
232 all_ elements are equal : True
233 all_ elements are equal : True
234 all_ elements are equal : True
235 all_ elements are equal : True
236 all_ elements are equal : True
237 all_ elements are equal : True
238 all_ elements are equal : True
239 all_ elements are equal : True
240 all_ elements are equal : True
241 all_ elements are equal : True
242 all_ elements are equal : True
243 all_ elements are equal : True
244 all_ elements are equal : True
245 all_ elements are equal : True
246 all_ elements are equal : True
247 all_ elements are equal : True
248 all_ elements are equal : True
249 all_ elements are equal : True
250 all_ elements are equal : True
251 all_ elements are equal : True
252 all_ elements are equal : True
253 all_ elements are equal : True
254 all_ elements are equal : True
255 all_ elements are equal : True
256 all_ elements are equal : True
257 all_ elements are equal : True
258 all_ elements are equal : True
259 all_ elements are equal : True
260 all_ elements are equal : True
261 all_ elements are equal : True
262 all_ elements are equal : True
263 all_ elements are equal : True
264 all_ elements are equal : True
265 all_ elements are equal : True
266 all_ elements are equal : True
267 all_ elements are equal : True
268 all_ elements are equal : True
269 all_ elements are equal : True
270 all_ elements are equal : True
271 all_ elements are equal : True
272 all_ elements are equal : True
273 all_ elements are equal : True
274 all_ elements are equal : True
275 all_ elements are equal : True
276 all_ elements are equal : True
277 all_ elements are equal : True
278 all_ elements are equal : True
279 all_ elements are equal : True
280 all_ elements are equal : True
281 all_ elements are equal : True
282 all_ elements are equal : True
283 all_ elements are equal : True
284 all_ elements are equal : True
285 all_ elements are equal : True
286 all_ elements are equal : True
287 all_ elements are equal : True
288 all_ elements are equal : True
289 all_ elements are equal : True
290 all_ elements are equal : True
291 all_ elements are equal : True
292 all_ elements are equal : True
293 all_ elements are equal : True
294 all_ elements are equal : True
295 all_ elements are equal : True
296 all_ elements are equal : True
297 all_ elements are equal : True
298 all_ elements are equal : True
299 all_ elements are equal : True
300 all_ elements are equal : True
301 all_ elements are equal : True
302 all_ elements are equal : True
303 all_ elements are equal : True
304 all_ elements are equal : True
305 all_ elements are equal : True
306 all_ elements are equal : True
307 all_ elements are equal : True
308 all_ elements are equal : True
309 all_ elements are equal : True
310 all_ elements are equal : True
311 all_ elements are equal : True
312 all_ elements are equal : True
313 all_ elements are equal : True
314 all_ elements are equal : True
315 all_ elements are equal : True
316 all_ elements are equal : True
317 all_ elements are equal : True
318 all_ elements are equal : True
319 all_ elements are equal : True
320 all_ elements are equal : True
321 all_ elements are equal : True
322 all_ elements are equal : True
323 all_ elements are equal : True
324 all_ elements are equal : True
325 all_ elements are equal : True
326 all_ elements are equal : True
327 all_ elements are equal : True
328 all_ elements are equal : True
329 all_ elements are equal : True
330 all_ elements are equal : True
331 all_ elements are equal : True
332 all_ elements are equal : True
333 all_ elements are equal : True
334 all_ elements are equal : True
335 all_ elements are equal : True
336 all_ elements are equal : True
337 all_ elements are equal : True
338 all_ elements are equal : True
339 all_ elements are equal : True
340 all_ elements are equal : True
341 all_ elements are equal : True
342 all_ elements are equal : True
343 all_ elements are equal : True
344 all_ elements are equal : True
345 all_ elements are equal : True
346 all_ elements are equal : True
347 all_ elements are equal : True
348 all_ elements are equal : True
349 all_ elements are equal : True
350 all_ elements are equal : True
351 all_ elements are equal : True
352 all_ elements are equal : True
353 all_ elements are equal : True
354 all_ elements are equal : True
355 all_ elements are equal : True
356 all_ elements are equal : True
357 all_ elements are equal : True
358 all_ elements are equal : True
359 all_ elements are equal : True
360 all_ elements are equal : True
361 all_ elements are equal : True
362 all_ elements are equal : True
363 all_ elements are equal : True
364 all_ elements are equal : True
365 all_ elements are equal : True
366 all_ elements are equal : True
367 all_ elements are equal : True
368 all_ elements are equal : True
369 all_ elements are equal : True
370 all_ elements are equal : True
371 all_ elements are equal : True
372 all_ elements are equal : True
373 all_ elements are equal : True
374 all_ elements are equal : True
375 all_ elements are equal : True
376 all_ elements are equal : True
377 all_ elements are equal : True
378 all_ elements are equal : True
379 all_ elements are equal : True
380 all_ elements are equal : True
381 all_ elements are equal : True
382 all_ elements are equal : True
383 all_ elements are equal : True
384 all_ elements are equal : True
385 all_ elements are equal : True
386 all_ elements are equal : True
387 all_ elements are equal : True
388 all_ elements are equal : True
389 all_ elements are equal : True
390 all_ elements are equal : True
391 all_ elements are equal : True
392 all_ elements are equal : True
393 all_ elements are equal : True
394 all_ elements are equal : True
395 all_ elements are equal : True
396 all_ elements are equal : True
397 all_ elements are equal : True
398 all_ elements are equal : True
399 all_ elements are equal : True
400 all_ elements are equal : True
401 all_ elements are equal : True
402 all_ elements are equal : True
403 all_ elements are equal : True
404 all_ elements are equal : True
405 all_ elements are equal : True
406 all_ elements are equal : True
407 all_ elements are equal : True
408 all_ elements are equal : True
409 all_ elements are equal : True
410 all_ elements are equal : True
411 all_ elements are equal : True
412 all_ elements are equal : True
413 all_ elements are equal : True
414 all_ elements are equal : True
415 all_ elements are equal : True
416 all_ elements are equal : True
417 all_ elements are equal : True
418 all_ elements are equal : True
419 all_ elements are equal : True
420 all_ elements are equal : True
421 all_ elements are equal : True
422 all_ elements are equal : True
423 all_ elements are equal : True
424 all_ elements are equal : True
425 all_ elements are equal : True
426 all_ elements are equal : True
427 all_ elements are equal : True
428 all_ elements are equal : True
429 all_ elements are equal : True
430 all_ elements are equal : True
431 all_ elements are equal : True
432 all_ elements are equal : True
433 all_ elements are equal : True
434 all_ elements are equal : True
435 all_ elements are equal : True
436 all_ elements are equal : True
437 all_ elements are equal : True
438 all_ elements are equal : True
439 all_ elements are equal : True
440 all_ elements are equal : True
441 all_ elements are equal : True
442 all_ elements are equal : True
443 all_ elements are equal : True
444 all_ elements are equal : True
445 all_ elements are equal : True
446 all_ elements are equal : True
447 all_ elements are equal : True
448 all_ elements are equal : True
449 all_ elements are equal : True
450 all_ elements are equal : True
451 all_ elements are equal : True
452 all_ elements are equal : True
453 all_ elements are equal : True
454 all_ elements are equal : True
455 all_ elements are equal : True
456 all_ elements are equal : True
457 all_ elements are equal : True
458 all_ elements are equal : True
459 all_ elements are equal : True
460 all_ elements are equal : True
461 all_ elements are equal : True
462 all_ elements are equal : True
463 all_ elements are equal : True
464 all_ elements are equal : True
465 all_ elements are equal : True
466 all_ elements are equal : True
467 all_ elements are equal : True
468 all_ elements are equal : True
469 all_ elements are equal : True
470 all_ elements are equal : True
471 all_ elements are equal : True
472 all_ elements are equal : True
473 all_ elements are equal : True
474 all_ elements are equal : True
475 all_ elements are equal : True
476 all_ elements are equal : True
477 all_ elements are equal : True
478 all_ elements are equal : True
479 all_ elements are equal : True
480 all_ elements are equal : True
481 all_ elements are equal : True
482 all_ elements are equal : True
483 all_ elements are equal : True
484 all_ elements are equal : True
485 all_ elements are equal : True
486 all_ elements are equal : True
487 all_ elements are equal : True
488 all_ elements are equal : True
489 all_ elements are equal : True
490 all_ elements are equal : True
491 all_ elements are equal : True
492 all_ elements are equal : True
493 all_ elements are equal : True
494 all_ elements are equal : True
495 all_ elements are equal : True
496 all_ elements are equal : True
497 all_ elements are equal : True
498 all_ elements are equal : True
499 all_ elements are equal : True
500 all_ elements are equal : True
501 all_ elements are equal : True
502 all_ elements are equal : True
503 all_ elements are equal : True
504 all_ elements are equal : True
505 all_ elements are equal : True
506 all_ elements are equal : True
507 all_ elements are equal : True
508 all_ elements are equal : True
509 all_ elements are equal : True
510 all_ elements are equal : True
511 all_ elements are equal : True
512 all_ elements are equal : True
513 all_ elements are equal : True
514 all_ elements are equal : True
515 all_ elements are equal : True
516 all_ elements are equal : True
517 all_ elements are equal : True
518 all_ elements are equal : True
519 all_ elements are equal : True
520 all_ elements are equal : True
521 all_ elements are equal : True
522 all_ elements are equal : True
523 all_ elements are equal : True
524 all_ elements are equal : True
525 all_ elements are equal : True
526 all_ elements are equal : True
527 all_ elements are equal : True
528 all_ elements are equal : True
529 all_ elements are equal : True
530 all_ elements are equal : True
531 all_ elements are equal : True
532 all_ elements are equal : True
533 all_ elements are equal : True
534 all_ elements are equal : True
535 all_ elements are equal : True
536 all_ elements are equal : True
537 all_ elements are equal : True
538 all_ elements are equal : True
539 all_ elements are equal : True
540 all_ elements are equal : True
541 all_ elements are equal : True
542 all_ elements are equal : True
543 all_ elements are equal : True
544 all_ elements are equal : True
545 all_ elements are equal : True
546 all_ elements are equal : True
547 all_ elements are equal : True
548 all_ elements are equal : True
549 all_ elements are equal : True
550 all_ elements are equal : True
551 all_ elements are equal : True
552 all_ elements are equal : True
553 all_ elements are equal : True
554 all_ elements are equal : True
555 all_ elements are equal : True
556 all_ elements are equal : True
557 all_ elements are equal : True
558 all_ elements are equal : True
559 all_ elements are equal : True
560 all_ elements are equal : True
561 all_ elements are equal : True
562 all_ elements are equal : True
563 all_ elements are equal : True
564 all_ elements are equal : True
565 all_ elements are equal : True
566 all_ elements are equal : True
567 all_ elements are equal : True
568 all_ elements are equal : True
569 all_ elements are equal : True
570 all_ elements are equal : True
571 all_ elements are equal : True
572 all_ elements are equal : True
573 all_ elements are equal : True

In [54]:
# 100 - 
# 200 - 
# 300 -
# 400 -
# 500 -

# all -

In [51]:
dict_data = {"Direccion": all_address,
             "Precio" : all_price,
             "UF" : all_uf,
             "m2_Construidos" : all_cons_m2,
             "m2_totales" : all_total_m2,
             "Habitaciones" :  all_num_bedrooms,
             "Banos" : all_num_bathrooms,
             "Estacionamientos" : all_parkings_slots,
             "Publi": all_publi_date}

In [52]:
df = pd.DataFrame(dict_data)

In [53]:
df

,Direccion,Precio,UF,m2_Construidos,m2_totales,Habitaciones,Banos,Estacionamientos,Publi
0,"San Miguel, Cuarta Avenida 1447",99245550,2850.000,49,49,2,1,0,19/12/2022
1,"Estación Central, Avenida Padre Alberto Hurtado",75000000,2153.749,62,62,3,2,0,19/12/2022
2,"Independencia, Inglaterra",68949540,1980.000,39,39,2,1,0,19/12/2022
3,"San Joaquín, Sta. Rosa 2648",70342460,2020.000,46,46,2,1,0,19/12/2022
4,"Las Condes, Fray Luis de León",971561700,27900.000,340,340,4,3,3,19/12/2022
...,...,...,...,...,...,...,...,...,...
9914,"Independencia, Gomero",69646000,2000.000,70,70,1,1,0,04/12/2022
9915,"Las Condes, Cristobal colon / felix de amesti",390017600,11200.000,147,147,4,3,3,04/12/2022
9916,"Santiago, Vicuña Mackenna / Metro Irarrázaval ...",73128300,2100.000,33,33,1,1,0,04/12/2022
9917,"Pudahuel, San pablo ag/el salistre",80000000,2297.332,65,65,3,2,1,04/12/2022
9918,"Las Condes, Avenida Cristóbal Colón & Sebastiá...",328868412,9444.000,115,115,3,3,1,04/12/2022

In [39]:
df_601_800

,Direccion,Precio,UF,m2_Construidos,m2_totales,Habitaciones,Banos,Estacionamientos,Publi
0,"Vitacura, Sector:Parque Arauco/Av.Presidente K...",630296300,18100.0,220,220,4,3,0,12/12/2022
1,"Ñuñoa, Venta de departamento en exequiel ferná...",135809700,3900.0,65,65,3,2,0,12/12/2022
2,"Macul, Departamentos nuevos de 1d+1b cerca a m...",95763250,2750.0,38,38,1,1,0,12/12/2022
3,"Santiago, Departamento con 2d + 1b y terraza. ...",111085370,3190.0,48,48,2,1,0,12/12/2022
4,"La Florida, Santa Victoria, La Florida",125258331,3597.0,47,47,2,1,0,12/12/2022
...,...,...,...,...,...,...,...,...,...
1984,"Estación Central, Coronel Souper",104120770,2990.0,68,68,2,2,1,10/12/2022
1985,"Santiago, General Jofre / Portugal",118398200,3400.0,50,50,2,1,1,10/12/2022
1986,"Providencia, Av. Manuel Montt, Providencia",125362800,3600.0,42,42,1,1,0,10/12/2022
1987,"Providencia, Las Hortensias",435287500,12500.0,173,173,4,3,2,10/12/2022
1988,"Santiago, San Isidro 96",84619890,2430.0,35,35,1,1,0,10/12/2022

In [28]:
df_401_600

,Direccion,Precio,UF,m2_Construidos,m2_totales,Habitaciones,Banos,Estacionamientos,Publi
0,"Santiago, san martin 873",68845071,1977.000,30,30,1,1,0,13/12/2022
1,"Providencia, Av Suecia - Nueva providencia/Lyo...",139292000,4000.000,38,38,1,1,0,13/12/2022
2,"Providencia, Metro los leones",165409250,4750.000,60,60,2,1,1,13/12/2022
3,"Recoleta, esquina avda el salto",121880500,3500.000,65,65,2,2,0,13/12/2022
4,"Santiago, Nataniel Cox/Eleuterio Ramírez",102727850,2950.000,65,65,2,2,0,13/12/2022
...,...,...,...,...,...,...,...,...,...
1964,"Independencia, Depto de 2d+1b, cerca de metro ...",95415020,2740.000,3702,3702,2,1,0,12/12/2022
1965,"Santiago, Depto con 1d + 1b y terraza, a pasos...",90539800,2600.000,36,36,1,1,0,12/12/2022
1966,"Macul, Luis Valenzuela arias",125362800,3600.000,62,62,2,2,1,12/12/2022
1967,"Recoleta, Depto de 3d+1b+terraza. A 2 cuadras ...",95000000,2728.082,55,55,3,1,0,12/12/2022
1968,"Santiago, Departamento amoblado con 1d + 1b, t...",97504400,2800.000,32,32,1,1,0,12/12/2022

In [14]:
df_201_400

,Direccion,Precio,UF,m2_Construidos,m2_totales,Habitaciones,Banos,Estacionamientos,Publi
0,"Las Condes, Apoquindo, escuela militar",137550850,3950.0,44,44,1,1,0,16/12/2022
1,"Las Condes, Golda Meir / Escuela Militar",677307350,19450.0,280,280,4,4,2,16/12/2022
2,"San Miguel, Rivas / Gran Av. José Miguel Carrera",69646000,2000.0,38,38,1,1,0,16/12/2022
3,"Independencia, Rivera con Barnechea",69646000,2000.0,38,38,1,1,0,16/12/2022
4,"Vitacura, Presidente Kennedy 3368",329077350,9450.0,170,170,3,2,1,16/12/2022
...,...,...,...,...,...,...,...,...,...
1968,"Ñuñoa, Pedro de Valdivia / Crecente errázuriz",177597300,5100.0,76,76,2,2,1,13/12/2022
1969,"Lo Barnechea, Avenida La Dehesa/Club de Golf",1589147605,45635.0,390,390,3,4,0,13/12/2022
1970,"Santiago, Santa Isabel",83052855,2385.0,41,41,1,1,0,13/12/2022
1971,"Santiago, Lord cochrane nu-57576/eleuterio rám...",62681400,1800.0,30,30,1,1,0,13/12/2022
1972,"Macul, Arturo Prat 4327",168891550,4850.0,59,59,2,2,0,13/12/2022

In [7]:
df_0_200

,Direccion,Precio,UF,m2_Construidos,m2_totales,Habitaciones,Banos,Estacionamientos,Publi
0,"Estación Central, Avenida Padre Alberto Hurtado",75000000,2153.749,62,62,3,2,0,19/12/2022
1,"Independencia, Inglaterra",68949540,1980.000,39,39,2,1,0,19/12/2022
2,"San Joaquín, Sta. Rosa 2648",70342460,2020.000,46,46,2,1,0,19/12/2022
3,"Las Condes, Fray Luis de León",971561700,27900.000,340,340,4,3,3,19/12/2022
4,"La Florida, Rafael Matus",45269900,1300.000,39,39,2,1,0,19/12/2022
...,...,...,...,...,...,...,...,...,...
1973,"Ñuñoa, Ñuñoa, Región Metropolitana",255000000,7322.746,95,95,3,2,0,16/12/2022
1974,"Santiago, Paris / Metro Santa Lucía",70000000,2010.166,47,47,1,1,0,16/12/2022
1975,"Ñuñoa, Dublé Almeyda / Campos de Deporte",195008800,5600.000,69,69,2,2,0,16/12/2022
1976,"Santiago, Santiago, Región Metropolitana",99000000,2842.949,60,60,2,2,1,16/12/2022
1977,"Maipú, Maipú, Región Metropolitana",110000000,3158.832,65,65,3,2,1,16/12/2022

In [91]:
# df.drop_duplicates

<bound method DataFrame.drop_duplicates of                                               Direccion     Precio        UF  \
0     Providencia, ¡Mira! Aquí está, Carmen Sylva / ...  240000116  6892.000
1                             Santiago, Sta. Isabel 431   97504400  2800.000
2                             La Florida, Tobalaba 7321   87057500  2500.000
3                           Las Condes, Vital Apoquindo   87000000  2498.349
4                              Quinta Normal, Carrascal   68000000  1952.732
...                                                 ...        ...       ...
5944                           Santiago, Sargento Aldea   66163700  1900.000
5945                                 Santiago, Tarapacá  128845100  3700.000
5946  Providencia, Padre mariano / metro p. De valdivia  174811460  5020.000
5947                Macul, Vicuña Mackenna / Av. Quilín  146256600  4200.000
5948                   Quinta Normal, martinez de rozas   51886270  1490.000

      m2_Construidos  m2_totales  Habitaciones  Banos  Estacionamientos  \
0                 86          86             2      3                 1
1                 48          48             2      2                 0
2                 55          55             3      2                 1
3                  0           0             3      1                 0
4                  0           0             2      1                 0
...              ...         ...           ...    ...               ...
5944              29          29             1      1                 0
5945              60          60             1      1                 0
5946              63          63             1      1                 0
5947              60          60             2      2                 1
5948              20          20             1      1                 0

           Publi
0     19/12/2022
1     18/12/2022
2     18/12/2022
3     18/12/2022
4     18/12/2022
...          ...
5944  10/12/2022
5945  10/12/2022
5946  10/12/2022
5947  10/12/2022
5948  10/12/2022

[5949 rows x 9 columns]>

In [ ]:
# acuerdate de comentar la siguiente celda despues de guardar el csv y cambiarle a nombre al archivo para que no se te sobreescriba

In [47]:
df.to_excel("data/pisos_rm.xlsx", index = False)